apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootapp
  name: springbootapp-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springbootapp